/**
 * Created by qianqian.li on 2016/11/17.
 */
export const SHOW_PAGE_LOADING = 'SHOW_PAGE_LOADING';
export const HIDE_PAGE_LOADING = 'HIDE_PAGE_LOADING';
export const SHOW_ERROR_TIP = 'SHOW_ERROR_TIP';
export const ERROR_TIP_TEXT = 'ERROR_TIP_TEXT';

export const SEND_LOGIN = 'SEND_LOGIN';
export const SEND_LOGIN_OUT = 'SEND_LOGIN_OUT';
//app list
export const GET_NEWEST_APP_LIST = 'GET_NEWEST_APP_LIST';
export const CLEAR_NEWEST_APP_LIST = 'CLEAR_NEWEST_APP_LIST';

export const GET_APP_LIST = 'GET_APP_LIST';
export const CLEAR_APP_LIST = 'CLEAR_APP_LIST';

export const GET_APP_COMMENT_ALL_LIST = 'GET_APP_COMMENT_ALL_LIST';
export const CLEAR_APP_COMMENT_ALL_LIST = 'CLEAR_APP_COMMENT_ALL_LIST';

export const GET_USER_INFO = 'GET_USER_INFO';

export const GET_HONOUR_CUR_WEEK_LIST = 'GET_HONOUR_CUR_WEEK_LIST';
export const CLEAR_HONOUR_CUR_WEEK_LIST = 'CLEAR_HONOUR_CUR_WEEK_LIST';

export const GET_HONOUR_RED_CUR_WEEK_LIST = 'GET_HONOUR_RED_CUR_WEEK_LIST';
export const GET_HONOUR_BLACK_CUR_WEEK_LIST = 'GET_HONOUR_BLACK_CUR_WEEK_LIST';
export const GET_HONOUR_DATE_LIST = 'GET_HONOUR_DATE_LIST';
export const GET_CURRENT_WEEK_DATE = 'GET_CURRENT_WEEK_DATE';

export const GET_HONOUR_RED_DATE_LIST = 'GET_HONOUR_RED_DATE_LIST';
export const GET_HONOUR_BLACK_DATE_LIST = 'GET_HONOUR_BLACK_DATE_LIST';
export const COUNT_DOWNLOAD = 'COUNT_DOWNLOAD';
export const GET_APP_DETAIL = 'GET_APP_DETAIL';

export const GET_APP_COMMENT_LIST = 'GET_APP_COMMENT_LIST';
export const CLEAR_APP_COMMENT_LIST = 'CLEAR_APP_COMMENT_LIST';

export const GET_USER_COMMENT_LIST = 'GET_USER_COMMENT_LIST';
export const CLEAR_USER_COMMENT_LIST = 'CLEAR_USER_COMMENT_LIST';

export const GET_HONOUR_HISTORY = 'GET_HONOUR_HISTORY';
export const CLEAR_HONOUR_HISTORY = 'CLEAR_HONOUR_HISTORY';


export const GET_HONOUR_RED_HISTORY_LIST = 'GET_HONOUR_RED_HISTORY_LIST';
export const GET_HONOUR_BLACK_HISTORY_LIST = 'GET_HONOUR_BLACK_HISTORY_LIST';
export const UPLOAD_IMG = 'UPLOAD_IMG';
export const ADD_UPLOADED_IMG = 'ADD_UPLOADED_IMG';
export const REMOVE_UPLOADED_IMG = 'REMOVE_UPLOADED_IMG';
export const CLEAR_UPLOADED_IMG = 'CLEAR_UPLOADED_IMG';
export const SAVE_COMMENT = 'SAVE_COMMENT';